import { assert, assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { createInteractionsHandler, GENERIC_ERROR, validResourceId } from "./vaultInteractionsR2.ts";
const origin="https://app.faithmariah.com";
function fixture(auth=true){const calls:{name:string,args:Record<string,unknown>}[]=[];const logs:unknown[]=[];return {calls,logs,handler:createInteractionsHandler({authenticate:async()=>auth?{id:"11111111-1111-4111-8111-111111111111",email:"member@example.com"}:null,rpc:async(name,args)=>{calls.push({name,args});return {data:{ok:true}};},log:(...x)=>logs.push(x)},origin)};}
const req=(body:unknown,headers:Record<string,string>={})=>new Request("https://edge.test",{method:"POST",headers:{origin,"authorization":"Bearer token","content-type":"application/json",...headers},body:typeof body==="string"?body:JSON.stringify(body)});
Deno.test("exact origin preflight and disallowed/missing origin fail closed",async()=>{const f=fixture();let r=await f.handler(new Request("https://edge.test",{method:"OPTIONS",headers:{origin}}));assertEquals(r.status,204);assertEquals(r.headers.get("access-control-allow-origin"),origin);r=await f.handler(new Request("https://edge.test",{method:"OPTIONS",headers:{origin:"https://evil.test"}}));assertEquals(r.status,403);assertEquals(r.headers.get("access-control-allow-origin"),null);r=await f.handler(new Request("https://edge.test",{method:"POST"}));assertEquals(r.status,403);});
Deno.test("auth, caller identity fields, malformed and bounded chunked bodies are generic",async()=>{let f=fixture(false),r=await f.handler(req({action:"get_interaction"}));assertEquals(r.status,401);assertEquals(await r.json(),GENERIC_ERROR);f=fixture();r=await f.handler(req({action:"get_interaction",userId:"forged"}));assertEquals(r.status,400);r=await f.handler(req("{PRIVATE_SENTINEL"));assertEquals(r.status,400);assert(!JSON.stringify(f.logs).includes("PRIVATE_SENTINEL"));const stream=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode("x".repeat(9000)));c.close();}});r=await f.handler(new Request("https://edge.test",{method:"POST",headers:{origin,authorization:"Bearer token"},body:stream}));assertEquals(r.status,413);});
Deno.test("canonical and safe producer resource IDs map to fixed RPC while unsafe delimiters fail",async()=>{const f=fixture();const id="22222222-2222-4222-8222-222222222222",membership=`membershipio:${"a".repeat(64)}`;assert(validResourceId("replay-1"));assert(validResourceId(membership));const maxId="A"+"._~:-az09".repeat(30).slice(0,219);assertEquals(maxId.length,220);assert(validResourceId(maxId));assert(validResourceId("membershipio:"+"A".repeat(64)));assert(validResourceId("replay:1"));for(const unsafe of ["../replay","replay/1"," replay-1","replay-1?x=1","A".repeat(221)]){assert(!validResourceId(unsafe),unsafe);const rejected=await f.handler(req({action:"begin_session",resourceId:unsafe,targetKind:"moment",targetId:id}));assertEquals(rejected.status,400,unsafe);}let r=await f.handler(req({action:"begin_session",resourceId:membership,targetKind:"moment",targetId:id}));assertEquals(r.status,200);assertEquals(f.calls[0].name,"replay_vault_begin_session");assertEquals(f.calls[0].args.p_user_id,"11111111-1111-4111-8111-111111111111");assertEquals(f.calls[0].args.p_email,"member@example.com");r=await f.handler(req({action:"begin_session",resourceId:"replay-1",targetKind:"moment",targetId:id}));assertEquals(r.status,200);r=await f.handler(req({action:"begin_session",resourceId:"replay-1",targetKind:"moment",targetId:"forged"}));assertEquals(r.status,400);});
Deno.test("fixed log taxonomy excludes request payload and generic envelope",async()=>{const logs:unknown[]=[];const handler=createInteractionsHandler({authenticate:async()=>({id:"11111111-1111-4111-8111-111111111111",email:"x@y.com"}),rpc:async()=>({data:null,error:{code:"42501"}}),log:(...x)=>logs.push(x)},origin);const id="22222222-2222-4222-8222-222222222222";const r=await handler(req({action:"get_interaction",resourceId:"private-sentinel",targetKind:"moment",targetId:id}));assertEquals(r.status,403);assertEquals(await r.json(),GENERIC_ERROR);assert(!JSON.stringify(logs).includes("private-sentinel"));assert(JSON.stringify(logs).includes("rpc_rejected"));});

Deno.test("full replay bookmark uses canonical resource target without caller timestamp or scopes",async()=>{
 const f=fixture();const resourceId=`membershipio:${"a".repeat(64)}`;
 const r=await f.handler(req({action:"set_bookmark",resourceId,targetKind:"replay",saved:true}));
 assertEquals(r.status,200);assertEquals(f.calls.at(-1)?.name,"replay_vault_set_bookmark");
 assertEquals(f.calls.at(-1)?.args.p_target_kind,"replay");assertEquals(f.calls.at(-1)?.args.p_target_id,null);
 for(const forged of [{scopes:["replay_vault"]},{timestamp:"2020-01-01"}]){const denied=await f.handler(req({action:"set_bookmark",resourceId,targetKind:"replay",saved:true,...forged}));assertEquals(denied.status,400);}
});
