import { bearerHeader, readBoundedJson, responseHeaders, secureJson } from './replayVaultAccess.ts';
import { memberSafeText } from './replayVaultProducer.mjs';

export const RESOURCE_ID = /^[A-Za-z0-9][A-Za-z0-9._~:-]{0,219}$/;
const ACTIONS = new Set(['browse', 'categories', 'transcript', 'questions', 'saved']);
const ALLOWED: Record<string, Set<string>> = {
  browse: new Set(['action', 'category', 'cursor', 'limit']),
  categories: new Set(['action', 'cursor', 'limit']),
  transcript: new Set(['action', 'resourceId', 'afterIndex', 'cursor', 'limit']),
  questions: new Set(['action', 'resourceId', 'cursor', 'limit']),
  saved: new Set(['action', 'filter', 'cursor', 'limit']),
};
const PRIVATE_KEY = /(locator|dropbox|source.?url|playback.?url|permanent.?url|provider|path|file.?id|user.?id|access.?scope|timestamp|as.?of)/i;
export const LIBRARY_ERROR = { error: 'Replay Vault request unavailable' } as const;

type Body = Record<string, unknown>;
export type LibraryUser = { id: string };
export type LibraryDependencies = { isAllowedOrigin(req: Request): boolean; authenticate(bearer: string): Promise<LibraryUser | null>; rpc(name: string, args: Record<string, unknown>): Promise<{ data: unknown; error?: unknown }>; log(requestId: string, taxonomy: 'auth_rejected'|'request_rejected'|'rpc_rejected'|'internal_error'): void };
type MappedRequest = { rpc: string; args: Record<string, unknown>; action: string; pageLimit: number };
const integer=(value:unknown,fallback:number,maximum:number)=>Number.isSafeInteger(value)&&Number(value)>0?Math.min(Number(value),maximum):fallback;
const text=(value:unknown,maximum:number)=>typeof value==='string'&&value.trim().length>0&&value.trim().length<=maximum?value.trim():null;
function hasPrivateShape(value: unknown, depth=0): boolean { if(depth>8)return true;if(!value||typeof value!=='object')return false;if(Array.isArray(value))return value.some(v=>hasPrivateShape(v,depth+1));return Object.entries(value as Record<string,unknown>).some(([k,v])=>PRIVATE_KEY.test(k)||hasPrivateShape(v,depth+1)); }
function decodeCursor(value:unknown):string|null { if(value==null||value==='')return null;if(typeof value!=='string'||value.length>1000||!/^[A-Za-z0-9_-]+$/.test(value))return '__invalid__';try{const raw=atob(value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4));const parsed=JSON.parse(raw);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?JSON.stringify(parsed):'__invalid__';}catch{return '__invalid__';} }
function encodeCursor(raw:unknown):string|null { if(typeof raw!=='string'||!raw.startsWith('{')||raw.length>900)return null;try{JSON.parse(raw);return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}catch{return null;} }

export function mapLibraryRequest(body:unknown,userId:string):MappedRequest|null {
 if(!body||typeof body!=='object'||Array.isArray(body)||hasPrivateShape(body))return null;const r=body as Body;const action=text(r.action,24);if(!action||!ACTIONS.has(action))return null;
 if(Object.keys(r).some(k=>!ALLOWED[action].has(k)))return null;const cursor=decodeCursor(r.cursor);if(cursor==='__invalid__')return null;const requested=integer(r.limit,action==='browse'?20:action==='transcript'?100:60,100);const base={p_user_id:userId,p_limit:requested+1};
 if(action==='browse')return{action,rpc:'replay_vault_browse_member',args:{...base,p_category:text(r.category,120),p_cursor:cursor},pageLimit:requested};
 if(action==='categories')return{action,rpc:'replay_vault_categories_member',args:{...base,p_cursor:cursor},pageLimit:requested};
 if(action==='transcript'){const id=text(r.resourceId,220);if(!id||!RESOURCE_ID.test(id))return null;let after=-1;if(cursor){try{after=Number(JSON.parse(cursor).afterIndex)}catch{return null;}}else if(Number.isSafeInteger(r.afterIndex))after=Math.max(-1,Number(r.afterIndex));if(!Number.isSafeInteger(after)||after>10000000)return null;return{action,rpc:'replay_vault_transcript_member',args:{...base,p_portal_resource_id:id,p_after_index:after},pageLimit:requested};}
 if(action==='questions'){const id=text(r.resourceId,220);if(r.resourceId!=null&&(!id||!RESOURCE_ID.test(id)))return null;return{action,rpc:'replay_vault_questions_member',args:{...base,p_portal_resource_id:id,p_cursor:cursor},pageLimit:requested};}
 const filter=text(r.filter,16)??'all';if(!['all','videos','moments'].includes(filter))return null;return{action,rpc:'replay_vault_saved_member',args:{...base,p_filter:filter,p_cursor:cursor},pageLimit:requested};
}
function mapRows(action:string,rows:Record<string,unknown>[]){return rows.map(row=>{if(action==='transcript')return{cueId:String(row.cue_id??''),cueIndex:Number(row.cue_index),startSeconds:Number(row.start_seconds),endSeconds:Number(row.end_seconds),text:memberSafeText(row.cue_text,1000)};if(action==='questions')return{questionId:String(row.question_id??''),resourceId:String(row.portal_resource_id??''),title:memberSafeText(row.title,160,'Replay'),category:memberSafeText(row.category,120,'Replay'),question:memberSafeText(row.question,400),answerSummary:memberSafeText(row.answer_summary,600),answerer:memberSafeText(row.answerer,120),startSeconds:Number(row.start_seconds),endSeconds:Number(row.end_seconds)};if(action==='saved')return{bookmarkId:String(row.bookmark_id??''),resourceId:String(row.portal_resource_id??''),title:memberSafeText(row.title,160,'Replay'),category:memberSafeText(row.category,120,'Replay'),targetKind:String(row.target_kind??''),targetId:String(row.target_id??''),startSeconds:Number(row.cue_seconds),savedAt:String(row.saved_at??''),label:memberSafeText(row.label,400)};return{resourceId:String(row.portal_resource_id??''),title:memberSafeText(row.title,160,'Replay'),category:memberSafeText(row.category,120,'Replay'),durationSeconds:Number(row.duration_seconds),publishedAt:typeof row.published_at==='string'?row.published_at:null,questionCount:Number(row.question_count??0)};});}
export function createMemberLibraryHandler(deps:LibraryDependencies){return async(req:Request)=>{const requestId=crypto.randomUUID();if(!deps.isAllowedOrigin(req)){deps.log(requestId,'request_rejected');return secureJson(req,LIBRARY_ERROR,404);}if(req.method==='OPTIONS')return new Response(null,{status:204,headers:responseHeaders(req)});if(req.method!=='POST')return secureJson(req,LIBRARY_ERROR,405);try{const bearer=bearerHeader(req);if(!bearer){deps.log(requestId,'auth_rejected');return secureJson(req,LIBRARY_ERROR,401);}const user=await deps.authenticate(bearer);if(!user){deps.log(requestId,'auth_rejected');return secureJson(req,LIBRARY_ERROR,401);}const body=await readBoundedJson<Body>(req);const mapped=mapLibraryRequest(body,user.id);if(!mapped){deps.log(requestId,'request_rejected');return secureJson(req,LIBRARY_ERROR,400);}const result=await deps.rpc(mapped.rpc,mapped.args);if(result.error){deps.log(requestId,'rpc_rejected');return secureJson(req,LIBRARY_ERROR,503);}const all=Array.isArray(result.data)?result.data as Record<string,unknown>[]:[];const hasMore=all.length>mapped.pageLimit;const visible=all.slice(0,mapped.pageLimit);const nextCursor=hasMore&&visible.length?encodeCursor(visible[visible.length-1].row_cursor):null;if(hasMore&&!nextCursor){deps.log(requestId,'rpc_rejected');return secureJson(req,LIBRARY_ERROR,503);}if(mapped.action==='categories')return secureJson(req,{categories:visible.map(row=>({category:memberSafeText(row.category,120,'Replay'),resourceCount:Number(row.resource_count??0)})),nextCursor});return secureJson(req,{items:mapRows(mapped.action,visible),nextCursor});}catch(error){deps.log(requestId,error instanceof Error&&['request_too_large','invalid_json'].includes(error.message)?'request_rejected':'internal_error');const status=error instanceof Error&&error.message==='request_too_large'?413:error instanceof Error&&error.message==='invalid_json'?400:500;return secureJson(req,LIBRARY_ERROR,status);}};}
