const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const SAFE_RESOURCE=/^[A-Za-z0-9][A-Za-z0-9._~:-]{0,219}$/;
const obj=x=>x&&typeof x==='object'&&!Array.isArray(x)?x:null;
const num=x=>typeof x==='number'&&Number.isFinite(x)&&x>=0?x:null;
export function validInteractionResourceId(value){return typeof value==='string'&&SAFE_RESOURCE.test(value);}
export function interactionTarget(target){if(!validInteractionResourceId(target?.resourceId))return null;if(UUID.test(target?.questionId??''))return {resourceId:target.resourceId,targetKind:'question',targetId:target.questionId};if(UUID.test(target?.momentId??''))return {resourceId:target.resourceId,targetKind:'moment',targetId:target.momentId};return null;}
export function createSequencedEventQueue(initialSequence,transmit){let nextSequence=initialSequence;let tail=Promise.resolve();return{enqueue(eventId,payload){const run=async()=>{const sequence=nextSequence;const body={...payload,eventId,sequence};let failure;for(let attempt=0;attempt<2;attempt++){try{const receipt=await transmit(body);if(!receipt||receipt.nextSequence!==sequence+1)throw new Error('invalid_receipt');nextSequence=receipt.nextSequence;return receipt;}catch(error){failure=error;}}throw failure;};const result=tail.then(run);tail=result.then(()=>undefined,()=>undefined);return result;},nextSequence(){return nextSequence;}};}
export function watchReceipt(value){const x=obj(value);if(!x)return null;const duration=num(x.durationSeconds),watched=num(x.watchedSeconds),last=num(x.lastPositionSeconds);if(duration===null||duration<=0||watched===null||last===null||typeof x.completed!=='boolean')return null;return {watchedSeconds:watched,durationSeconds:duration,lastPositionSeconds:last,completed:x.completed};}
export function loadReceipt(value,target){const x=obj(value),t=obj(x?.target);if(!x||!t||t.resourceId!==target.resourceId||t.targetKind!==target.targetKind||t.targetId!==target.targetId||!UUID.test(t.playbackAttemptId??''))return null;const w=watchReceipt(x.watch);if(!w)return null;const b=x.bookmark===null?null:bookmarkReceipt(x.bookmark,target);if(x.bookmark!==null&&!b)return null;return {bookmark:b,watch:w};}
export function bookmarkReceipt(value,target){const x=obj(value);if(!x||!UUID.test(x.bookmarkId??'')||x.resourceId!==target.resourceId||x.targetKind!==target.targetKind||x.targetId!==target.targetId)return null;return {bookmarkId:x.bookmarkId,resourceId:x.resourceId,targetKind:x.targetKind,targetId:x.targetId};}
export function bookmarkMutationReceipt(value,target){const x=obj(value);if(!x||typeof x.saved!=='boolean'||typeof x.changed!=='boolean'||x.resourceId!==target.resourceId||x.targetKind!==target.targetKind||x.targetId!==target.targetId)return null;return x;}
export function sessionReceipt(value,target){const x=obj(value),w=watchReceipt(x);if(!x||!w||!UUID.test(x.sessionId??'')||!UUID.test(x.playbackAttemptId??'')||x.targetKind!==target.targetKind||x.targetId!==target.targetId||!Number.isSafeInteger(x.nextSequence)||x.nextSequence<1||typeof x.expiresAt!=='string')return null;return {...w,sessionId:x.sessionId,playbackAttemptId:x.playbackAttemptId,nextSequence:x.nextSequence,expiresAt:x.expiresAt};}
export function eventReceipt(value,eventId,sequence){const x=obj(value),w=watchReceipt(x);if(!x||!w||x.eventId!==eventId||x.acceptedSequence!==sequence||x.nextSequence!==sequence+1||typeof x.replayed!=='boolean')return null;return {...w,eventId,nextSequence:x.nextSequence,replayed:x.replayed};}
export function noteReceipt(value,target){const x=obj(value);if(!x||!UUID.test(x.noteId??'')||typeof x.openPath!=='string'||!/^\/notes\?page=[0-9a-f-]{36}$/i.test(x.openPath)||x.resourceId!==target.resourceId||x.targetKind!==target.targetKind||x.targetId!==target.targetId)return null;return {noteId:x.noteId,openPath:x.openPath,replayed:Boolean(x.replayed)};}
