import { isStableVaultId } from './replayVaultCore.mjs';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const CURSOR=/^[A-Za-z0-9_-]{1,1000}$/;
const finite=(v)=>Number.isFinite(v)?Math.max(0,Number(v)):null;
const safe=(v,max)=>typeof v==='string'?v.replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,max):'';
export function normalizeCursor(data){return data?.nextCursor===null||data?.nextCursor===undefined?null:CURSOR.test(data.nextCursor)?data.nextCursor:undefined;}
export function normalizeBrowse(data){if(!Array.isArray(data?.items)||normalizeCursor(data)===undefined)return null;return data.items.map(x=>isStableVaultId(x?.resourceId)?{resourceId:x.resourceId,title:safe(x.title,160)||'Replay',category:safe(x.category,120)||'Replay',durationSeconds:finite(x.durationSeconds),publishedAt:typeof x.publishedAt==='string'?x.publishedAt:null,questionCount:Number.isSafeInteger(x.questionCount)?Math.max(0,x.questionCount):0}:null).filter(Boolean);}
export function normalizeCategories(data){if(!Array.isArray(data?.categories)||normalizeCursor(data)===undefined)return null;return data.categories.map(x=>({category:safe(x?.category,120),resourceCount:Number.isSafeInteger(x?.resourceCount)?Math.max(0,x.resourceCount):0})).filter(x=>x.category);}
export function normalizeTranscript(data,resourceId){if(!Array.isArray(data?.items)||!isStableVaultId(resourceId)||normalizeCursor(data)===undefined)return null;return data.items.map(x=>UUID.test(x?.cueId)&&Number.isSafeInteger(x?.cueIndex)&&finite(x?.startSeconds)!==null&&safe(x?.text,1000)?{cueId:x.cueId,cueIndex:x.cueIndex,startSeconds:finite(x.startSeconds),endSeconds:finite(x.endSeconds),text:safe(x.text,1000)}:null).filter(Boolean);}
export function normalizeQuestions(data){if(!Array.isArray(data?.items)||normalizeCursor(data)===undefined)return null;return data.items.map(x=>UUID.test(x?.questionId)&&isStableVaultId(x?.resourceId)&&finite(x?.startSeconds)!==null?{questionId:x.questionId,resourceId:x.resourceId,title:safe(x.title,160)||'Replay',category:safe(x.category,120)||'Replay',question:safe(x.question,400),answerSummary:safe(x.answerSummary,600),answerer:safe(x.answerer,120)||null,startSeconds:finite(x.startSeconds),endSeconds:finite(x.endSeconds)}:null).filter(Boolean);}
export function normalizeSaved(data){if(!Array.isArray(data?.items)||normalizeCursor(data)===undefined)return null;return data.items.map(x=>UUID.test(x?.bookmarkId)&&isStableVaultId(x?.resourceId)&&['replay','moment','question'].includes(x?.targetKind)&&UUID.test(x?.targetId)?{bookmarkId:x.bookmarkId,resourceId:x.resourceId,title:safe(x.title,160)||'Replay',category:safe(x.category,120)||'Replay',targetKind:x.targetKind,targetId:x.targetId,startSeconds:finite(x.startSeconds),savedAt:typeof x.savedAt==='string'?x.savedAt:null,label:safe(x.label,400)}:null).filter(Boolean);}
export function activeCueIndex(cues,time){if(!Number.isFinite(time)||!cues.length)return -1;for(let i=0;i<cues.length;i+=1){const start=Number(cues[i]?.startSeconds),end=Number(cues[i]?.endSeconds);if(Number.isFinite(start)&&Number.isFinite(end)&&start<=time&&time<end)return i;if(Number.isFinite(start)&&start>time)break;}return -1;}
