import { RefObject, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import type { PlaybackResult, PlaybackTarget } from './types';
import { bookmarkMutationReceipt, bookmarkReceipt, createSequencedEventQueue, eventReceipt, interactionTarget, loadReceipt, noteReceipt, sessionReceipt } from './interactionCore.mjs';

type LoadState='loading'|'ready'|'failed';
type SyncState='idle'|'pending'|'failed';
type Bookmark={bookmarkId:string;resourceId:string;targetKind:'moment'|'question';targetId:string};
type EventResult={watchedSeconds:number;durationSeconds:number;lastPositionSeconds:number;completed:boolean;eventId:string;nextSequence:number;replayed:boolean};
type EventQueue={enqueue:(eventId:string,payload:Record<string,unknown>)=>Promise<EventResult>};
const invoke=async(body:Record<string,unknown>)=>{const {data,error}=await supabase.functions.invoke('vault-member-interactions',{body});if(error||!data||typeof data!=='object'||!('data'in data))throw new Error('unavailable');return (data as {data:unknown}).data;};

export function useVaultInteractions(playback:PlaybackResult,target:PlaybackTarget,videoRef:RefObject<HTMLVideoElement>,sourceGeneration:number){
 const canonical=useMemo(()=>interactionTarget({resourceId:target.resourceId,momentId:target.momentId,questionId:target.questionId}),[target.resourceId,target.momentId,target.questionId]);
 const generation=useRef(0),session=useRef<{id:string;events:EventQueue}|null>(null),lastSent=useRef(0),noteRequest=useRef<string|null>(null);
 const [loadState,setLoadState]=useState<LoadState>('loading'),[sessionState,setSessionState]=useState<LoadState>('loading'),[syncState,setSyncState]=useState<SyncState>('idle');
 const [bookmark,setBookmark]=useState<Bookmark|null>(null),[watch,setWatch]=useState({watchedSeconds:0,durationSeconds:0,lastPositionSeconds:0,completed:false}),[bookmarkBusy,setBookmarkBusy]=useState(false),[noteBusy,setNoteBusy]=useState(false),[status,setStatus]=useState(''),[note,setNote]=useState<{openPath:string}|null>(null);
 const load=useCallback(async()=>{if(!canonical){setLoadState('failed');setStatus('Saved actions are unavailable for this answer.');return;}const g=generation.current;setLoadState('loading');try{const receipt=loadReceipt(await invoke({action:'get_interaction',...canonical}),canonical);if(!receipt)throw new Error();if(g!==generation.current)return;setBookmark(receipt.bookmark);setWatch(receipt.watch);setLoadState('ready');}catch{if(g===generation.current){setLoadState('failed');setStatus('Saved actions could not be loaded. Retry.');}}},[canonical]);
 useEffect(()=>{generation.current++;session.current=null;setSessionState(playback.provider==='youtube'?'failed':'loading');setSyncState('idle');setStatus('');setNote(null);void load();},[playback.resourceId,playback.provider,sourceGeneration,canonical,load]);
 const begin=useCallback(async()=>{if(!canonical||session.current||playback.provider==='youtube')return;const g=generation.current;setSessionState('loading');try{const r=sessionReceipt(await invoke({action:'begin_session',...canonical}),canonical);if(!r)throw new Error();if(g!==generation.current)return;const id=r.sessionId;const events=createSequencedEventQueue(r.nextSequence,async(body:Record<string,unknown>)=>{if(g!==generation.current||session.current?.id!==id)throw new Error('stale_generation');const eventId=String(body.eventId),sequence=Number(body.sequence);const parsed=eventReceipt(await invoke({action:'media_event',sessionId:id,...body}),eventId,sequence);if(!parsed)throw new Error('invalid_receipt');return parsed;});session.current={id,events};setWatch(r);setSessionState('ready');}catch{if(g===generation.current){setSessionState('failed');setStatus('Watch progress could not start. Playback still works.');}}},[canonical,playback.provider]);
 const send=useCallback((eventType:'timeupdate'|'pause'|'seeked'|'ended',media:HTMLVideoElement)=>{const s=session.current;if(!s)return;if(eventType==='timeupdate'&&Date.now()-lastSent.current<2000)return;lastSent.current=Date.now();const g=generation.current,eventId=crypto.randomUUID(),payload={eventType,positionMs:Math.round(Math.max(0,media.currentTime)*1000),clientDurationMs:Number.isFinite(media.duration)?Math.round(media.duration*1000):null};setSyncState('pending');void s.events.enqueue(eventId,payload).then((r)=>{if(g!==generation.current||session.current?.id!==s.id)return;setWatch(r);setSyncState('idle');}).catch(()=>{if(g===generation.current&&session.current?.id===s.id){setSyncState('failed');setStatus('Watch progress is saved locally in the player, but is not synced. Retry by pausing again.');}});},[]);
 useEffect(()=>{const media=videoRef.current;if(!media||playback.provider==='youtube')return;const play=()=>void begin();const time=()=>{if(!media.paused&&document.visibilityState==='visible')send('timeupdate',media);};const seek=()=>send('seeked',media),pause=()=>send('pause',media),ended=()=>send('ended',media);media.addEventListener('play',play);media.addEventListener('timeupdate',time);media.addEventListener('seeked',seek);media.addEventListener('pause',pause);media.addEventListener('ended',ended);return()=>{media.removeEventListener('play',play);media.removeEventListener('timeupdate',time);media.removeEventListener('seeked',seek);media.removeEventListener('pause',pause);media.removeEventListener('ended',ended);};},[begin,playback.provider,send,sourceGeneration,videoRef]);
 const toggleBookmark=async()=>{if(!canonical||loadState!=='ready'||bookmarkBusy)return;const g=generation.current;setBookmarkBusy(true);setStatus(bookmark?'Removing saved answer…':'Saving answer…');try{const raw=await invoke({action:'set_bookmark',...canonical,saved:!bookmark});const mutation=bookmarkMutationReceipt(raw,canonical);if(!mutation)throw new Error();if(g!==generation.current)return;if(mutation.saved){const b=bookmarkReceipt(raw,canonical);if(!b)throw new Error();setBookmark(b);setStatus('Answer saved.');}else if(mutation.changed){setBookmark(null);setStatus('Saved answer removed.');}else setStatus('This answer was already removed.');}catch{if(g===generation.current)setStatus('Saved answer was not changed. Retry.');}finally{if(g===generation.current)setBookmarkBusy(false);}};
 const createNote=async()=>{if(!canonical||loadState!=='ready'||noteBusy)return;const g=generation.current;noteRequest.current??=crypto.randomUUID();setNoteBusy(true);setStatus('Creating note…');try{const r=noteReceipt(await invoke({action:'create_note',...canonical,positionMs:Math.round((videoRef.current?.currentTime??target.startSeconds??0)*1000),requestId:noteRequest.current}),canonical);if(!r)throw new Error();if(g!==generation.current)return;noteRequest.current=null;setNote(r);setStatus(r.replayed?'Existing note confirmed.':'Note created and confirmed.');}catch{if(g===generation.current)setStatus('Note was not created. Retry uses the same safe request.');}finally{if(g===generation.current)setNoteBusy(false);}};
 const resume=()=>{const media=videoRef.current;if(media&&watch.lastPositionSeconds>0){media.currentTime=Math.min(watch.lastPositionSeconds,Math.max(0,(media.duration||Infinity)-.25));setStatus(`Ready to resume at ${Math.floor(watch.lastPositionSeconds/60)}:${String(Math.floor(watch.lastPositionSeconds%60)).padStart(2,'0')}.`);}};
 return{available:Boolean(canonical),loadState,sessionState,syncState,bookmark,watch,bookmarkBusy,noteBusy,status,note,toggleBookmark,createNote,resume,retryLoad:load};
}
