import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { activeCueIndex, normalizeCursor, normalizeTranscript } from './replayVaultLibraryCore.mjs';
import { formatCompactTime, formatSpokenTime } from './replayVaultCore.mjs';
import type { PlaybackTarget } from './types';
type Cue={cueId:string;cueIndex:number;startSeconds:number;endSeconds:number|null;text:string};const PAGE_SIZE=100;const MAX_PAGES=500;
export function VaultTranscript({resourceId,title,currentTime,timeSynchronized=true,onOpen}:{resourceId:string;title:string;currentTime:number;timeSynchronized?:boolean;onOpen:(target:PlaybackTarget)=>void}){
 const[state,setState]=useState<'loading'|'ready'|'empty'|'error'>('loading');const[cues,setCues]=useState<Cue[]>([]);const[selected,setSelected]=useState<string|null>(null);const generation=useRef(0);
 const load=useCallback(async()=>{const own=++generation.current;setState('loading');setCues([]);setSelected(null);try{const all:Cue[]=[];let cursor:string|null=null;for(let page=0;page<MAX_PAGES;page+=1){const{data,error}=await supabase.functions.invoke('vault-member-library',{body:{action:'transcript',resourceId,cursor,limit:PAGE_SIZE}});if(own!==generation.current)return;const rows=error?null:normalizeTranscript(data,resourceId) as Cue[]|null;const next=error?undefined:normalizeCursor(data);if(!rows||next===undefined||rows.some((cue,index)=>index>0&&cue.cueIndex<=rows[index-1].cueIndex)){setState('error');return;}all.push(...rows);if(!next){setCues(all);setState(all.length?'ready':'empty');return;}cursor=next;}setState('error');}catch{if(own===generation.current)setState('error');}},[resourceId]);
 useEffect(()=>{void load();return()=>{generation.current+=1;}},[load]);const active=useMemo(()=>timeSynchronized?activeCueIndex(cues,currentTime):-1,[cues,currentTime,timeSynchronized]);
 return <section aria-labelledby="vault-transcript-heading" className="space-y-3 rounded-lg border p-3" data-vault-transcript><div><h3 id="vault-transcript-heading" className="font-semibold">Full transcript</h3><p className="text-sm text-muted-foreground">{timeSynchronized?'Complete authorized text alternative. Choose a cue to seek to its exact approved time.':'Transcript timing cannot synchronize with this external player. Choose a cue to reopen the player at that approved time.'}</p></div>{state==='loading'&&<p role="status" aria-live="polite" className="text-sm text-muted-foreground">Loading the complete authorized transcript…</p>}{state==='error'&&<div role="alert" className="space-y-2"><p className="text-sm">The complete transcript is temporarily unavailable, so partial text has not been shown as complete. This does not mean your access changed.</p><Button type="button" variant="outline" className="min-h-11" onClick={()=>void load()}>Retry transcript</Button></div>}{state==='empty'&&<p role="status" className="text-sm text-muted-foreground">No approved transcript text is available for this replay yet.</p>}{state==='ready'&&<ol className="max-h-96 space-y-1 overflow-y-auto" aria-label={`Transcript cues for ${title}`}>{cues.map((cue,index)=><li key={cue.cueId}><button type="button" aria-current={timeSynchronized&&index===active?'true':undefined} data-selected={cue.cueId===selected?'true':undefined} className="min-h-11 w-full rounded-md border px-3 py-2 text-left text-sm hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 aria-[current=true]:border-primary aria-[current=true]:bg-primary/10 data-[selected=true]:border-primary" aria-label={`${timeSynchronized?'Seek':'Open'} ${title} at ${formatSpokenTime(cue.startSeconds)}. ${cue.text}`} onClick={()=>{setSelected(cue.cueId);onOpen({resourceId,title,startSeconds:cue.startSeconds,questionId:null,momentId:cue.cueId});}}><span className="mr-2 font-semibold text-primary">{formatCompactTime(cue.startSeconds)}</span>{cue.text}</button></li>)}</ol>}</section>;
}
