// Platform Scorecard Data — 15 platforms with strategic profiles

export interface PlatformProfile {
  id: string;
  name: string;
  emoji: string;
  idealFor: string;
  bestWhen: string;
  strengths: string[];
  effort: 'Low' | 'Medium' | 'High';
  timeToResults: string;
  contentType: string;
  growthSpeed: 1 | 2 | 3 | 4 | 5;
}

export const PLATFORMS: PlatformProfile[] = [
  {
    id: 'instagram',
    name: 'Instagram',
    emoji: '📸',
    idealFor: 'Visual brands, lifestyle, coaching',
    bestWhen: 'You love creating reels and carousels',
    strengths: ['Visual storytelling', 'Reels virality', 'DM selling'],
    effort: 'High',
    timeToResults: '3-6 months',
    contentType: 'Short-form visual',
    growthSpeed: 3,
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    emoji: '💼',
    idealFor: 'B2B, consulting, professional services',
    bestWhen: 'Your clients are professionals or business owners',
    strengths: ['Organic reach', 'Thought leadership', 'Long-form text posts'],
    effort: 'Medium',
    timeToResults: '1-3 months',
    contentType: 'Text & articles',
    growthSpeed: 4,
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    emoji: '🎵',
    idealFor: 'Mass awareness, trending topics',
    bestWhen: 'You can create quick, personality-driven videos',
    strengths: ['Explosive reach', 'Algorithm-driven discovery', 'Gen Z / Millennial audience'],
    effort: 'Medium',
    timeToResults: '1-3 months',
    contentType: 'Short-form video',
    growthSpeed: 5,
  },
  {
    id: 'youtube',
    name: 'YouTube',
    emoji: '📺',
    idealFor: 'Evergreen authority, tutorials, education',
    bestWhen: 'You can teach or share deep expertise on camera',
    strengths: ['Search-driven traffic', 'Evergreen content', 'Deep trust building'],
    effort: 'High',
    timeToResults: '6-12 months',
    contentType: 'Long-form video',
    growthSpeed: 2,
  },
  {
    id: 'podcast',
    name: 'Podcast',
    emoji: '🎙️',
    idealFor: 'Deep connection, storytelling, expert positioning',
    bestWhen: 'You love talking and have stories to share',
    strengths: ['Intimate connection', 'Passive listening', 'Guest networking'],
    effort: 'Medium',
    timeToResults: '6-12 months',
    contentType: 'Long-form audio',
    growthSpeed: 2,
  },
  {
    id: 'facebook',
    name: 'Facebook',
    emoji: '👥',
    idealFor: 'Community building, groups, paid ads',
    bestWhen: 'Your audience is 35+ or you want to run ads',
    strengths: ['Groups for community', 'Mature ad platform', 'Event promotion'],
    effort: 'Medium',
    timeToResults: '1-3 months',
    contentType: 'Mixed media',
    growthSpeed: 3,
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    emoji: '𝕏',
    idealFor: 'Quick takes, networking, tech/business niche',
    bestWhen: 'You think in punchy one-liners and hot takes',
    strengths: ['Fast networking', 'Thread virality', 'Real-time engagement'],
    effort: 'Low',
    timeToResults: '1-3 months',
    contentType: 'Short-form text',
    growthSpeed: 4,
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    emoji: '📌',
    idealFor: 'Evergreen traffic, visual products, DIY',
    bestWhen: 'Your content solves problems people search for',
    strengths: ['Search engine traffic', 'Evergreen pins', 'Low maintenance'],
    effort: 'Low',
    timeToResults: '3-6 months',
    contentType: 'Visual pins',
    growthSpeed: 3,
  },
  {
    id: 'blog',
    name: 'Blog / SEO',
    emoji: '✍️',
    idealFor: 'Evergreen search traffic, authority',
    bestWhen: 'You enjoy writing and want passive traffic',
    strengths: ['Google search traffic', 'Evergreen authority', 'Repurposable content'],
    effort: 'High',
    timeToResults: '6-12 months',
    contentType: 'Long-form written',
    growthSpeed: 2,
  },
  {
    id: 'email-list',
    name: 'Email (Cold Outreach)',
    emoji: '📧',
    idealFor: 'B2B lead gen, freelancers, agencies',
    bestWhen: 'You have a specific target audience to reach directly',
    strengths: ['Direct access', 'High conversion', 'Personalized'],
    effort: 'Medium',
    timeToResults: '1-3 months',
    contentType: 'Personalized emails',
    growthSpeed: 3,
  },
  {
    id: 'networking',
    name: 'In-Person Networking',
    emoji: '🤝',
    idealFor: 'Local businesses, high-touch services',
    bestWhen: 'You thrive face-to-face and your market is local',
    strengths: ['High trust', 'Immediate relationships', 'Referral-driven'],
    effort: 'Medium',
    timeToResults: '1-3 months',
    contentType: 'In-person',
    growthSpeed: 3,
  },
  {
    id: 'speaking',
    name: 'Speaking / Summits',
    emoji: '🎤',
    idealFor: 'Authority building, lead gen at scale',
    bestWhen: 'You love presenting and want borrowed audiences',
    strengths: ['Borrowed audience', 'Authority positioning', 'List building'],
    effort: 'Medium',
    timeToResults: '1-3 months',
    contentType: 'Live presentations',
    growthSpeed: 4,
  },
  {
    id: 'collabs',
    name: 'Collaborations / JVs',
    emoji: '🤝',
    idealFor: 'Fast list growth, cross-promotion',
    bestWhen: 'You have peers with complementary audiences',
    strengths: ['Borrowed audience', 'Trust transfer', 'Win-win growth'],
    effort: 'Low',
    timeToResults: '1-3 months',
    contentType: 'Partnership',
    growthSpeed: 4,
  },
  {
    id: 'paid-ads',
    name: 'Paid Ads',
    emoji: '💰',
    idealFor: 'Scale fast with budget, proven offers',
    bestWhen: 'You have a proven offer and want to scale',
    strengths: ['Immediate traffic', 'Scalable', 'Targeted audience'],
    effort: 'Medium',
    timeToResults: 'Immediate',
    contentType: 'Ad creatives',
    growthSpeed: 5,
  },
  {
    id: 'threads',
    name: 'Threads',
    emoji: '🧵',
    idealFor: 'Text-first creators, Instagram crossover',
    bestWhen: 'You already have an Instagram following',
    strengths: ['Text-first format', 'Instagram integration', 'Growing platform'],
    effort: 'Low',
    timeToResults: '1-3 months',
    contentType: 'Short-form text',
    growthSpeed: 3,
  },
];
