// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { resilientAuthStorage } from '@/lib/resilientStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Resilient adapter: localStorage first, in-memory fallback for in-app
    // browsers (Instagram/Facebook/TikTok) and private-mode Safari.
    storage: resilientAuthStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
